security:

    encoders:
        Symfony\Component\Security\Core\User\UserInterface: bcrypt

    # https://symfony.com/doc/current/book/security.html#where-do-users-come-from-user-providers
    providers:
        players_in_memory:
            memory:
                users:
                    toto:
                        password: $2y$10$gOiZBQ1FNHOFFnZqJUgqxeLEXzzi0hHsRlKElp.VvMNfgJlZh5D3G
                        roles: ROLE_PLAYER
                    admin:
                        password: $2y$10$hZrVHLS0D/6VV6jjisU0rO5pEddAH29EhyUGnh1qMiWXjWnUHSFGq
                        roles: ROLE_PLAYER, ROLE_ADMIN

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            anonymous: ~
            form_login:
                login_path: app_main_index
                check_path: login_check
                username_parameter: player_username
                password_parameter: player_password
                csrf_parameter: csrf_player_token
                csrf_token_id: authenticate_player
                default_target_path: game_index
            logout:
                path: logout
                target: app_main_index
