#index:
#    path: /
#    defaults: { _controller: 'App\Controller\DefaultController::index' }

# first, run composer req annotations
controllers:
    resource: ../src/Controller/
    type: annotation

login_check:
    path: /login/check
    methods: [POST]

logout:
    path: /logout
