# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    app.game.dictionaries:
         - '%kernel.project_dir%/data/test.txt'
         - '%kernel.project_dir%/data/words.txt'
         - '%kernel.project_dir%/data/words.xml'

services:
    _defaults:
        public: false
        autowire: true

    App\:
        resource: '../src/*'
        exclude: '../src/{Entity,Repository}'

    App\Game\WordList:
        calls:
            - method: addLoader
              arguments: [txt, '@App\Game\Loader\TextFileLoader']
            - method: addLoader
              arguments: [xml, '@App\Game\Loader\XmlFileLoader']
            - method: loadDictionaries
              arguments: ['%app.game.dictionaries%']

    App\Game\GameRunner:
        public: true

